version: '{branch}.{build}'
  
branches:
  # whitelist
  only:
    - master
    - PHP-7.0

  # blacklist
  except:
    - PHP-7.0-Linux
    - PHP5

environment:
    MSSQL_PASSWORD: Password12!
    MSSQL_SERVERNAME: (local)\SQL2016
    MSSQL_USERNAME: sa
    PHP_VERSION: 7.0.14
    PHP_DEPSVER: 7.0
    PHP_SDK: c:\projects\php
#    REPORT_EXIT_STATUS: 1
    matrix:      
      - BUILD_PLATFORM: x64
        PHP_VC: 14
        PHP_TS: nts-Win32
        PHP_SDK_DIR: c:\projects\php\x64
        PHP_INSTALL_DIR: c:\projects\php\x64\bin
        platform: x64
        
# PHP_INSTALL_DIR is where the built PHP binaries go
# PHP_SDK_DIR is where PHP source is extracted to (e.g. PHP_SDK_DIR\php-7.0.14-src)
# PHP_SDK is where PHP sdk binary tools are extracted to
        
# Build worker image (VM template)
image: Visual Studio 2015

matrix:
  fast_finish: true
    
services:
  - mssql2016
  
# clone directory (or %APPVEYOR_BUILD_FOLDER%)
clone_folder: c:\projects\sqlphp

build:
    parallel: true                  # enable MSBuild parallel builds

install:
    - echo Downloading PHP-SDK
    - appveyor DownloadFile http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip    
    - move php-sdk-binary-tools-20110915.zip ..
    - echo Downloading PHP source code [%PHP_VERSION%]
#    - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/releases/php-' + ${env:PHP_VERSION} + '-' + ${env:PHP_TS} + '-VC' + ${env:PHP_VC} + '-' + ${env:BUILD_PLATFORM} + '.zip', ${env:APPVEYOR_BUILD_FOLDER} + '\..\php.zip')
    - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/releases/php-' + ${env:PHP_VERSION} + '-src.zip', ${env:APPVEYOR_BUILD_FOLDER} + '\..\php.zip')
    - echo Downloading PHP deps [%PHP_DEPSVER%]
    - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/php-sdk/deps-' + ${env:PHP_DEPSVER} + '-vc' + ${env:PHP_VC} + '-' + ${env:BUILD_PLATFORM} + '.7z', ${env:APPVEYOR_BUILD_FOLDER} + '\..\deps.7z')
    - echo Downloading MSODBC
    #32-bit https://download.microsoft.com/download/1/E/7/1E7B1181-3974-4B29-9A47-CC857B271AA2/English/X86/msodbcsql.msi
    - ps: (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/1/E/7/1E7B1181-3974-4B29-9A47-CC857B271AA2/English/X64/msodbcsql.msi', 'msodbcsql.msi')
    - ps: msiexec /i msodbcsql.msi /quiet /qn /norestart        
    - cd ..
    - cd
    - 7z x -y php-sdk-binary-tools-20110915.zip -o%PHP_SDK%
    - 7z x -y php.zip -o%PHP_SDK_DIR%
    - echo update SQL connection string
    - ps: (Get-Content ${env:APPVEYOR_BUILD_FOLDER}\test\pdo_sqlsrv\autonomous_setup.php) | ForEach-Object { $_ -replace "localhost",  ${env:MSSQL_SERVERNAME} -replace "<YourStrong!Passw0rd>",  ${env:MSSQL_PASSWORD} } | Set-Content ${env:APPVEYOR_BUILD_FOLDER}\test\pdo_sqlsrv\autonomous_setup.php
    - ps: (Get-Content ${env:APPVEYOR_BUILD_FOLDER}\test\sqlsrv\autonomous_setup.php) | ForEach-Object { $_ -replace "localhost",  ${env:MSSQL_SERVERNAME} -replace "<YourStrong!Passw0rd>",  ${env:MSSQL_PASSWORD} } | Set-Content ${env:APPVEYOR_BUILD_FOLDER}\test\sqlsrv\autonomous_setup.php
        
build_script:
    - '"C:\\Program Files (x86)\\Microsoft Visual Studio %PHP_VC%.0\\VC\\vcvarsall.bat" %BUILD_PLATFORM%'
    - Echo copy msphp code to ext folder
    - mkdir %PHP_SDK_DIR%\php-%PHP_VERSION%-src\ext\sqlsrv
    - mkdir %PHP_SDK_DIR%\php-%PHP_VERSION%-src\ext\pdo_sqlsrv
    - copy /Y %APPVEYOR_BUILD_FOLDER%\sqlsrv %PHP_SDK_DIR%\php-%PHP_VERSION%-src\ext\sqlsrv
    - copy /Y %APPVEYOR_BUILD_FOLDER%\pdo_sqlsrv %PHP_SDK_DIR%\php-%PHP_VERSION%-src\ext\pdo_sqlsrv
    - cd %PHP_SDK_DIR%\php-%PHP_VERSION%-src
    - cd
    - dir 
    - '%PHP_SDK%\bin\phpsdk_setvars.bat'
    - buildconf.bat
    - configure.bat --disable-all --disable-zts --enable-cli --enable-sqlsrv=shared --with-pdo-sqlsrv=shared --enable-pdo=shared --with-prefix=%PHP_INSTALL_DIR%
    - copy php.ini-development php.ini    
    - echo extension_dir=%PHP_INSTALL_DIR%\ext >> php.ini
    - echo extension=php_sqlsrv.dll >> php.ini
    - echo extension=php_pdo_sqlsrv.dll >> php.ini
    - nmake
    - nmake install
    - Echo copy php.ini and run-tests.php from php source to install directory.
    - copy php.ini %PHP_INSTALL_DIR%
    - copy run-tests.php %PHP_INSTALL_DIR%
    - dir %PHP_INSTALL_DIR%  

test_script:
    - cd %PHP_INSTALL_DIR%  
    - php --ini
    - php -i    
    - ps: .\php.exe run-tests.php -p php.exe ${env:APPVEYOR_BUILD_FOLDER}\test\sqlsrv\*.phpt | tee ${env:APPVEYOR_BUILD_FOLDER}\test\sqlsrv.log
    - ps: .\php.exe run-tests.php -p php.exe ${env:APPVEYOR_BUILD_FOLDER}\test\pdo_sqlsrv\*.phpt | tee ${env:APPVEYOR_BUILD_FOLDER}\test\pdo_sqlsrv.log    
   
after_test:
    - cd %APPVEYOR_BUILD_FOLDER%\test\
    - ps: Get-Content pdo_sqlsrv.log
    - python %APPVEYOR_BUILD_FOLDER%\test\output.py
    - ps: Get-Content nativeresult1.xml
    - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nativeresult1.xml))
    - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nativeresult2.xml))
    - ps: >- 
        [xml]$results = Get-Content tests/results/nativeresult1.xml 
        [xml]$results2 = Get-Content tests/results/nativeresult2.xml 
        $failure = $results.SelectSingleNode("//failure")
        $failure2 = $results2.SelectSingleNode("//failure")
        if ($failure -ne $null -Or $failure2 -ne $null) 
        { 
            $host.SetShouldExit(1)
            Write-Host "Forcing build failure due to phpt unit test failure(s)"
        }