#Download base image ubuntu 16.04

FROM ubuntu:16.04

# Update Ubuntu Software repository
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && \
	apt-get -y install \
	libxml2-dev \
	gcc	\
	g++ \
	autoconf \
	curl \
	make \
	locales \
	apt-transport-https	 \
	apt-utils \
	php7.0	\	
	php7.0-dev \
	unzip && apt-get clean
	

# set locale to utf-8
RUN locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

#install ODBC driver

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

#RUN echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/mssql-ubuntu-xenial-release/ xenial main" > /etc/apt/sources.list.d/mssqlpreview.list
#RUN apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql mssql-tools unixodbc-dev-utf16

#Either Install git / download zip (One can see other strategies : https://ryanfb.github.io/etc/2015/07/29/git_strategies_for_docker.html )
#Instead of installing git we are trying to get Source code from zip
#replace with your repository/branch as appropriate
RUN curl -sSL -o PHP-7.0-Linux.zip https://github.com/bob1913/msphpsql/archive/PHP-7.0-Linux.zip
RUN unzip PHP-7.0-Linux.zip -d /REPO/

WORKDIR /REPO/msphpsql-PHP-7.0-Linux/source/ 

RUN /bin/bash -c "./packagize.sh"

RUN echo "extension = pdo_sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
RUN echo "extension = sqlsrv.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

WORKDIR /REPO/msphpsql-PHP-7.0-Linux/source/sqlsrv
RUN phpize && ./configure && make && make install

WORKDIR /REPO/msphpsql-PHP-7.0-Linux/source/pdo_sqlsrv
RUN phpize && ./configure && make && make install

# set name of sql server host to use: sql
WORKDIR /REPO/msphpsql-PHP-7.0-Linux/test/pdo_sqlsrv
RUN sed -i -e 's/localhost/sql/g' autonomous_setup.php

WORKDIR /REPO/msphpsql-PHP-7.0-Linux/test/sqlsrv
RUN sed -i -e 's/localhost/sql/g' autonomous_setup.php

ENV REPORT_EXIT_STATUS 1
ENV TEST_PHP_EXECUTABLE /usr/bin/php
